# -*- coding: utf-8 -*-
"""Polars_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZtJe1SQV8GdmJff7wiKbv8EHj-S8Bm2
"""

import pandas as pd
import polars as pl
import numpy as np
import json
import random
from datetime import datetime, timedelta
import plotly.express as px

np.random.seed(42)
n_rows = 10000
user_ids = [f'u_{i}' for i in range(100,500)]
events = ['login','view_item','add_to_cart','checkout_start','purchase','error']

def dirty_price():
  val = round(random.uniform(10,500),2)
  if random.random() < 0.05: return f'€{val}'
  if random.random() < 0.05: return None
  return val

def generate_metadata():
  meta = {'browser': random.choice(['Chrome','Firefox','Safari']),
          'is_mobile': random.choice(['True','False'])}
  if random.random() < 0.1: return None
  return json.dumps(meta)

product_data = {
    'event_id': [f'evt_{i}' for i in range(n_rows)],
    'user_id': np.random.choice(user_ids + [None], n_rows),
    'event_name': np.random.choice(events, n_rows, p=[0.2,0.4,0.2,0.1,0.05,0.05]),
    'timestamp': [datetime(2024,1,1) + timedelta(minutes=random.randint(0,40000)) for _ in range(n_rows)],
    'price': [dirty_price() for _ in range(n_rows)],
    'metadata': [generate_metadata() for _ in range(n_rows)],
    'session_source': np.random.choice(['google','direct','meta','Google','META'], n_rows)
}

df_product = pd.DataFrame(product_data)

df_product = pd.concat([df_product,df_product.sample(200)])

df_product.to_csv('raw_product_data.csv', index=False)
print('Files ready: raw_product_data.csv')

"""# **Data Cleaning**"""

# Lazy Evaluation (Scan)
q1 = (
    pl.scan_csv('raw_product_data.csv')
    .unique()
    .filter(pl.col('user_id').is_not_null())
    .with_columns([
        pl.col('price')
        .str.replace(r'€','')
        .cast(pl.Float64,strict=False)
        .alias('price_clean'),

        pl.col('timestamp').str.to_datetime()
    ])
    .with_columns(
        pl.col('metadata')
        .str.json_decode(pl.Struct({'browser':pl.String,'is_mobile':pl.String}))
        .alias('meta_struct')
    )
    .unnest('meta_struct')
    .with_columns(
        pl.when(pl.col('is_mobile') == 'True')
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias('is_mobile')
    )
)

df_product_clean = q1.collect()
display(df_product_clean.head())

"""# **Metrics**"""

# Simple Funnel
funnel = (
    df_product_clean
    .filter(pl.col('event_name').is_in(['view_item','add_to_cart','purchase']))
    .group_by('event_name')
    .agg(pl.col('user_id').n_unique().alias('user_count'))
    .with_columns(
        pl.col('event_name')
        .replace_strict({'view_item': 1, 'add_to_cart':2, 'purchase':3}, default=99)
        .alias('step_order')
    )
    .sort('step_order')
)
display('Funnel:', funnel)

# AOV
aov = (
    df_product_clean
    .filter(pl.col('event_name')== 'purchase')
    .select(pl.col('price_clean').mean().round(0).alias('average_order_value'))
)
display('AOV:',aov)

# User Sessions
sessions = (
    df_product_clean
    .sort(['user_id','timestamp'])
    .with_columns([
        pl.col('timestamp').diff().over('user_id').alias('time_diff')
    ])
    .with_columns([
        pl.when((pl.col('time_diff').dt.total_seconds()> 1800) | (pl.col('time_diff').is_null()))
        .then(1)
        .otherwise(0)
        .alias('is_new_session')
    ])
    .with_columns([
        pl.col('is_new_session').cum_sum().alias('global_session_id')
    ])
)

display(sessions.select(['user_id','timestamp','is_new_session','global_session_id']).head(10))

"""# **Plotly**"""

# Aggregate Session Metrics
# Grouping by the calculate 'global_session_id
session_metrics = (
    sessions
    .group_by(['user_id','global_session_id'])
    .agg([
        pl.col('timestamp').min().alias('session_start'),
        pl.col('timestamp').max().alias('session_end'),
        pl.col('event_name').count().alias('event_count')
    ])
    .with_columns(
        (pl.col('session_end') - pl.col('session_start')).dt.total_minutes().alias('duration_minutes')
    )
    .filter(pl.col('duration_minutes') > 0)
    .sort('session_start')
)

display(session_metrics.head())

# Converting to Pandas because Plotly works better with Pandas
plot_df = session_metrics.select('duration_minutes').to_pandas()

fig_sessions = px.histogram(
    plot_df,
    x='duration_minutes',
    nbins=50,
    title='Session Distribution Lengths',
    labels= {'duration_minutes': 'Session Duration (Minutes)'},
    template = 'plotly_white'
)

median_val = plot_df['duration_minutes'].median()
fig_sessions.add_vline(x=median_val,line_dash='dash',line_color='red',annotation_text=f'Median:{median_val:.1f}m')

fig_sessions.show()

"""# **User Activity Gantt Chart**"""

# Filter for top 5 user so the chart is readable
top_users = (
    session_metrics
    .group_by('user_id')
    .agg(pl.count('global_session_id').alias('total_sessions'))
    .top_k(5, by='total_sessions')
    .select('user_id')
)

display(top_users)

timeline_df = (
    session_metrics
    .join(top_users, on='user_id',how='inner')
    .to_pandas()
)

display(timeline_df)

fig_timeline = px.timeline(
    timeline_df,
    x_start='session_start',
    x_end='session_end',
    y='user_id',
    color='event_count',
    title='User Session Timeline (Top 5 Users)',
    labels={'user_id':'User ID','event_count':'Events in Session'},
    template='plotly_white'
)

fig_timeline.update_yaxes(categoryorder='total ascending')

fig_timeline.show()

"""# **Time of Day Challenge**"""

tod_analytics = (
    session_metrics
    .with_columns(
        pl.col('session_start').dt.hour().alias('hour')
    )
    .with_columns(
        pl.when((pl.col('hour') >= 5) & (pl.col('hour') < 12))
        .then(pl.lit('Morning'))
        .when((pl.col('hour') >= 12) & (pl.col('hour') < 17))
        .then(pl.lit('Afternoon'))
        .when((pl.col('hour') >= 17) & (pl.col('hour') < 21))
        .then(pl.lit('Evening'))
        .otherwise(pl.lit('Night'))
        .alias('time_of_day')
    )
)

display(tod_analytics)

tod_stats = (
    tod_analytics
    .group_by('time_of_day')
    .agg([
        pl.col('duration_minutes').median().alias('median_duration'),
        pl.col('duration_minutes').count().alias('session_count')
    ])
    .with_columns(
        pl.col('time_of_day')
        .replace_strict({'Morning':1,'Afternoon':2,'Evening':3,'Night':4},default=5)
        .cast(pl.Int8)
        .alias('order')
    )
    .sort('order')
)
display(tod_stats)

fig_tod = px.box(
    tod_analytics.to_pandas(),
    x='time_of_day',
    y='duration_minutes',
    color='time_of_day',
    category_orders={'time_of_day':['Morning','Afternoon','Evening','Night']},
    title='Session Duration by Time of Day',
    labels={'duration_minutes':'Minutes','time_of_day':'Time of Day'},
    points='outliers'
)

fig_tod.show()