# -*- coding: utf-8 -*-
"""shoppingTrends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rdcS8XVTAMP-dcRRLkYLpF-TfECIdDT
"""

import pandas as pd
import numpy as np
import plotly.express as px

shopping_df = pd.read_csv('shopping_trends.csv')

# Checking the data

shopping_df.head()

shopping_df.info()

# describe(): Gives a summary of the numerical columns

shopping_df.describe()

# isna(): show the number of row that are empty

display(shopping_df.isna())

display(shopping_df.isna().sum())

# duplicate(): will show if there are any duplicates

print(shopping_df.duplicated().sum())

"""Age Histogram with Plotly"""

age = shopping_df['Age']

fig_age = px.histogram(
    age,
    x='Age'
)

fig_age.show()

# .columns: show the columns in a dataset

display(shopping_df.columns)

"""Bar Chart with Plotly"""

gender_dist = shopping_df['Gender'].value_counts().reset_index()

fig_gender = px.bar(
    gender_dist,
    x='Gender',
    y='count'
)

fig_gender.show()

"""Groupby()"""

shopping_df.columns

mean_purchases = shopping_df.groupby('Category')['Purchase Amount (USD)'].mean().round(2).sort_values(ascending=False)

display(mean_purchases)

"""# **sort_values()**"""

review_rating = shopping_df.sort_values('Review Rating',ascending=False)

display(review_rating)

"""Pie chart"""

subscription_status = shopping_df['Subscription Status'].value_counts().reset_index()

display(subscription_status)

fig_subscription = px.pie(
    subscription_status,
    values='count',
    names='Subscription Status',
    title='Subscription Status Distribution'
)

fig_subscription.show()

"""Most Popular Colors"""

top_5_colors = shopping_df['Color'].value_counts().head().reset_index()

display(top_5_colors)

fig_color = px.pie(
    top_5_colors,
    values='count',
    names='Color',
    title='Top Five Colors'
)

fig_color.show()

"""# **Previous Purchases**"""

fig_previous_purchases = px.scatter(
    shopping_df,
    x='Previous Purchases',
    y='Review Rating',
    title='Previous Purchases vs Review Rating'
)

fig_previous_purchases.show()