# -*- coding: utf-8 -*-
"""Streamflix_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrNSUoGO5aq_ouAM-GIiZOOR0tiwLWTW
"""

import polars as pl
import plotly.express as px
import numpy as np
import random

"""# **Data Cleaning**"""

df_streamflix_dirty = pl.read_csv('streamflix_raw_signups.csv')

df_streamflix_dirty.head()

ref_data = pl.DataFrame({
    'plan_type':['Basic','Premium','Family'],
    'plan_price':[5,10,25],
    'customer_support_calls': np.random.randint(0,20, size=3),
    'churned': np.random.choice(['Churned','Retained'], size=3)
})

df_streamflix_clean = (
    df_streamflix_dirty
    .with_columns([
      pl.col('full_name_raw')
        .str.replace_all(r'\n','') # Remove newlines
        .str.strip_chars() # Remove outer spaces
        .str.replace_all(r'\s+',' ') # Fix double spaces inside
        .str.to_titlecase() # Capitalize
        .alias('clean_name'),

      pl.col('email_raw')
        .str.replace('mailto:','')
        .alias('clean_email'),

      pl.col('user_id').str.slice(0,3).alias('id_prefix'),
      pl.col('user_id').str.slice(-4).alias('id_number'),
    ])
    .with_columns([
        pl.col('clean_name').str.split(' ').list.get(0).alias('first_name')
    ])
    .with_columns([
        pl.format('Hello {}, thanks for joining', pl.col('first_name')).alias('greeting_message')
    ])
    .join(ref_data, on='plan_type',how='left')
    .with_columns([
        (pl.col('plan_price') * 12).alias('annual_revenue')
    ])
)

df_streamflix_clean = df_streamflix_clean.select([
    'user_id',
    'clean_name',
    'clean_email',
    'plan_type',
    'minutes_watched',
    'plan_price',
    'annual_revenue',
    'customer_support_calls',
    'churned'
])

display(df_streamflix_clean.head())

df_streamflix_clean.write_csv('streamflix_final_report.csv')

"""# **EDA with Plotly**"""

# Creating a Product Metric: Engagement Score
df_streamflix_clean = df_streamflix_clean.with_columns([
    ((pl.col('minutes_watched')/ 100)- (pl.col('customer_support_calls')* 2)).alias('engagement_score')
])

df_streamflix_clean.head()

"""# **The 'Churn' Scatter Plot**"""

fig_churn = px.scatter(
    df_streamflix_clean.to_pandas(),
    x='minutes_watched',
    y='customer_support_calls',
    color='churned',
    title='StreamFlix: Impact of Support Calls on Churn',
    color_discrete_map={'Churned':'red','Retained':'blue'},
    opacity=0.6
)

fig_churn.update_layout(xaxis_title='Minutes Watched',yaxis_title='Customer Support Calls')
fig_churn.show()

"""# **The "Engagement" Box Plot**

**The Business Question:** "Which subscription plan has the healthiest engagement score? Are Family plan users actually watching more?
"""

fig_engagement = px.box(
    df_streamflix_clean.to_pandas(),
    x='plan_type',
    y='engagement_score',
    color='plan_type',
    title='Engagement Score Distribution by Plan',
    points='all'
)

fig_engagement.update_layout(xaxis_title='Subscription Plan', yaxis_title='Engagement Score')
fig_engagement.show()

"""# **The Correlation Heatmap**

**The Business Question:** "What metrics are actually related to each other?"
"""

# 1. Select only numeric columns
numeric_df = df_streamflix_clean.select([
    pl.col('minutes_watched'),
    pl.col('customer_support_calls'),
    pl.col('engagement_score')
])

# 2. Calculate Correlation Matrix
corr_matrix = numeric_df.corr()

fig_corr = px.imshow(
    corr_matrix.to_numpy(),
    x=numeric_df.columns,
    y=numeric_df.columns,
    text_auto=True,
    title='Correlation Heatmap',
    color_continuous_scale='Viridis'
)

fig_corr.show()